
export default class Constants {
  /**
   * 标签字体粗细 400.
   */
  static readonly LABEL_FONT_WEIGHT: number = 400;

  /**
   * 标题字体粗细 500.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * 商品项内边距 padding 12.
   */
  static readonly GOODS_ITEM_PADDING: number = 12;

  /**
   * 加载间隔时长 2000.
   */
  static readonly LOADING_DURATION: number = 2000;

  /**
   * 标题线数字 2.
   */
  static readonly TITLE_LINE_NUMBER: number = 2;

  /**
   * 100%.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * 商品分类百分比.
   */
  static readonly COMMODITYITEM_TITLE_PERCENT: string = '55%';
}
